<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="RAVI" failures="2" tests="2" name="Test(failed)" time="44.147" errors="0" timestamp="2023-03-29T20:43:39 IST">
  <testcase classname="testCases.TC_005_LoginTestDDT" name="test_LoginDDT" time="1.957">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at utilities.ExtentReportManager.onTestFailure(ExtentReportManager.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test_LoginDDT -->
  <testcase classname="testCases.TC_002_Check_Box" name="Check_Box" time="2.303">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at utilities.ExtentReportManager.onTestFailure(ExtentReportManager.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Check_Box -->
</testsuite> <!-- Test(failed) -->
